 
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import { NavBar } from "@/components/navbar";
import NextTopLoader from "nextjs-toploader";
import { Providers } from "./providers"; 
import type { Metadata } from "next";

// import { Pomodoro } from "@/components/pomodoro";
import dynamic from "next/dynamic";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Pomodoro = dynamic(() => import('../components/pomodoro'), {
  ssr: false,
});
 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Providers>
          <header>
          <NavBar />
          <NextTopLoader color="#2E78C7" height={2} />
          </header>
          {/* <div className="min-h-[calc(100vh-64px)]">{children}</div> */}
          {children}
          <div className="fixed bottom-0 right-2 m-4"><Pomodoro/></div>
         </Providers> 
        
      </body>
    </html>
  );
}
